# Generated by Django 4.1 on 2023-07-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='modelo',
            name='descripcion',
            field=models.CharField(max_length=340, null=True),
        ),
    ]
