# Generated by Django 4.2 on 2023-06-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_modelo_alter_producto_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Modelos'),
        ),
    ]
