# Generated by Django 4.2.1 on 2023-05-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_producto_aro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='aro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.aro'),
        ),
    ]
