# Generated by Django 4.2 on 2023-06-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_modelo_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aro',
            old_name='Aro',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='Genero',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='modelo',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='aro',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Aro'),
        ),
        migrations.AddField(
            model_name='genero',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genero',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Genero'),
        ),
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Marca'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Modelo'),
        ),
    ]
