# Generated by Django 4.2.1 on 2023-05-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_producto_aro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='genero',
        ),
        migrations.AlterField(
            model_name='aro',
            name='nombre',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
