# Generated by Django 4.2 on 2023-06-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_rename_aro_aro_nombre_rename_genero_genero_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aro',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
