# Generated by Django 4.2 on 2023-06-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_aro_descripcion_alter_genero_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aro',
            name='descripcion',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='descripcion',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='descripcion',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
