# Generated by Django 4.2.1 on 2023-05-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_genero_producto_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aro',
            old_name='nombre',
            new_name='Aro',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='nombre',
            new_name='Genero',
        ),
    ]
