# Generated by Django 4.2 on 2023-06-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_aro_descripcion_alter_genero_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aro',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
    ]
