# Generated by Django 4.1 on 2023-06-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='perfil',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador'), ('bodeguero', 'Bodeguero')], default='cliente', max_length=15),
        ),
    ]
